package zubair;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MUHAMMAD HUSSAIN
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    
      static String dblink="DESKTOP-NIBRUQ0",db="take",row[][]={},col[]={ "ID", "USERNAME","PASSWORD"},rowa[][]={},cola[]={ "ID", "NAME", "PRICE", "QUANTITY", "TOTAL PRICE"};
    static DefaultTableModel dtm,dtma;
      public admin() {
        initComponents();
       MEN3.setEnabled(false);
        MEN4.setEnabled(false);
  
       THANKS.setVisible(false);
       ar.setVisible(false);
       ad.setVisible(false);
       PA.setVisible(false);
       
       PD.setVisible(false);
       
       pu.setVisible(false);
     
        dtm=new DefaultTableModel(row,col);
       tb1.setModel(dtm);
        tb2.setModel(dtm);
        dtma=new DefaultTableModel(rowa,cola);
     tb3.setModel(dtma);
        tb4.setModel(dtma);
          tb5.setModel(dtma);
       
        
        dtm.getDataVector().removeAllElements();
             try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String a = "jdbc:sqlserver://"+dblink+";databaseName="+db+";integratedSecurity=true;";

            Connection con = DriverManager.getConnection(a);
            String q = "select * from emp";
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery(q);
             while (rs.next()) {
                 dtm.addRow(new Object[]{rs.getInt("id"),rs.getString("username"),rs.getString("password")});
                 
             }
         }catch (Exception ex) {
            System.out.println(ex);
        }     
        
dtma.getDataVector().removeAllElements();
             try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String a = "jdbc:sqlserver://"+dblink+";databaseName="+db+";integratedSecurity=true;";

            Connection con = DriverManager.getConnection(a);
            String q = "select * from pro";
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery(q);
             while (rs.next()) {
                 dtma.addRow(new Object[]{rs.getInt("id"),rs.getString("name"),rs.getInt("price"),rs.getInt("quantity"),rs.getInt("total_price")});
                 
             }
         }catch (Exception ex) {
            System.out.println(ex);
        }     
        
   
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        LOGIN = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ps = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        THANKS = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        psr = new javax.swing.JPasswordField();
        idr = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        usr = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        ad = new javax.swing.JPanel();
        idr1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        PA = new javax.swing.JPanel();
        pida = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        pnamea = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ppa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pqa = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb3 = new javax.swing.JTable();
        pu = new javax.swing.JPanel();
        pid = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        pp = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pq = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb4 = new javax.swing.JTable();
        PD = new javax.swing.JPanel();
        idd = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb5 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        MEN3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        MEN4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        jMenuItem4.setText("jMenuItem4");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));

        LOGIN.setAutoscrolls(true);
        LOGIN.setEnabled(false);
        LOGIN.setFocusCycleRoot(true);
        LOGIN.setPreferredSize(new java.awt.Dimension(800, 800));

        jLabel3.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zubair/LE.png"))); // NOI18N
        jLabel3.setText("PASSWORD :");

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zubair/8.png"))); // NOI18N
        jLabel1.setText("       ADMIN");

        ps.setMinimumSize(new java.awt.Dimension(6, 28));
        ps.setPreferredSize(new java.awt.Dimension(6, 28));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LOGINLayout = new javax.swing.GroupLayout(LOGIN);
        LOGIN.setLayout(LOGINLayout);
        LOGINLayout.setHorizontalGroup(
            LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGINLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(LOGINLayout.createSequentialGroup()
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LOGINLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ps, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LOGINLayout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jButton1)))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        LOGINLayout.setVerticalGroup(
            LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LOGINLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(LOGINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(572, Short.MAX_VALUE))
        );

        THANKS.setAutoscrolls(true);
        THANKS.setMinimumSize(new java.awt.Dimension(800, 800));
        THANKS.setPreferredSize(new java.awt.Dimension(800, 800));

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 36)); // NOI18N
        jLabel2.setText("                 ///  YOU ARE LOGINED \\\\\\");

            jLabel4.setText("YOUR TWO MENU ARE ENABLED IN MENU BAR FOR PROCEED");

            javax.swing.GroupLayout THANKSLayout = new javax.swing.GroupLayout(THANKS);
            THANKS.setLayout(THANKSLayout);
            THANKSLayout.setHorizontalGroup(
                THANKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
                .addGroup(THANKSLayout.createSequentialGroup()
                    .addGap(346, 346, 346)
                    .addComponent(jLabel4)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            THANKSLayout.setVerticalGroup(
                THANKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(THANKSLayout.createSequentialGroup()
                    .addGap(164, 164, 164)
                    .addComponent(jLabel2)
                    .addGap(57, 57, 57)
                    .addComponent(jLabel4)
                    .addContainerGap(539, Short.MAX_VALUE))
            );

            ar.setAutoscrolls(true);
            ar.setMinimumSize(new java.awt.Dimension(800, 800));

            jLabel5.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zubair/8.png"))); // NOI18N
            jLabel5.setText("USERNAME : ");

            jLabel6.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zubair/LE.png"))); // NOI18N
            jLabel6.setText("PASSWORD :");

            psr.setMinimumSize(new java.awt.Dimension(6, 28));
            psr.setPreferredSize(new java.awt.Dimension(6, 28));

            idr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            idr.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    idrActionPerformed(evt);
                }
            });

            jButton2.setBackground(new java.awt.Color(0, 0, 0));
            jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jButton2.setForeground(new java.awt.Color(255, 255, 255));
            jButton2.setText("ADD");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jLabel7.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
            jLabel7.setText("ID : ");

            usr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            usr.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    usrActionPerformed(evt);
                }
            });

            jButton3.setBackground(new java.awt.Color(0, 0, 0));
            jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jButton3.setForeground(new java.awt.Color(255, 255, 255));
            jButton3.setText("UPDATE");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });

            tb1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "ID", "USER NAME", "PASSWORD", "Title 4"
                }
            ));
            jScrollPane1.setViewportView(tb1);

            javax.swing.GroupLayout arLayout = new javax.swing.GroupLayout(ar);
            ar.setLayout(arLayout);
            arLayout.setHorizontalGroup(
                arLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(arLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(arLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(arLayout.createSequentialGroup()
                            .addGroup(arLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(arLayout.createSequentialGroup()
                                    .addGroup(arLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(arLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(psr, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(arLayout.createSequentialGroup()
                                            .addGroup(arLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel7))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(arLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(idr, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(usr, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(21, 21, 21))
                                .addGroup(arLayout.createSequentialGroup()
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(58, 58, 58)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 224, Short.MAX_VALUE))
                        .addComponent(jScrollPane1))
                    .addContainerGap())
            );
            arLayout.setVerticalGroup(
                arLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(arLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addGroup(arLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(idr, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(arLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(usr, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(arLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(psr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                    .addGroup(arLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            ad.setAutoscrolls(true);
            ad.setMinimumSize(new java.awt.Dimension(800, 800));

            idr1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            idr1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    idr1ActionPerformed(evt);
                }
            });

            jButton4.setBackground(new java.awt.Color(0, 0, 0));
            jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jButton4.setForeground(new java.awt.Color(255, 255, 255));
            jButton4.setText("DELETE");
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });

            jLabel10.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
            jLabel10.setText("ID : ");

            tb2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "ID", "USER NAME", "PASSWORD"
                }
            ));
            jScrollPane2.setViewportView(tb2);

            javax.swing.GroupLayout adLayout = new javax.swing.GroupLayout(ad);
            ad.setLayout(adLayout);
            adLayout.setHorizontalGroup(
                adLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(adLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(adLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(adLayout.createSequentialGroup()
                            .addGroup(adLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(adLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(idr1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(adLayout.createSequentialGroup()
                                    .addGap(101, 101, 101)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 458, Short.MAX_VALUE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                    .addContainerGap())
            );
            adLayout.setVerticalGroup(
                adLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(adLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addGroup(adLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(idr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(169, Short.MAX_VALUE))
            );

            PA.setAutoscrolls(true);
            PA.setMinimumSize(new java.awt.Dimension(800, 800));

            pida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            pida.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    pidaActionPerformed(evt);
                }
            });

            jButton5.setBackground(new java.awt.Color(0, 0, 0));
            jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jButton5.setForeground(new java.awt.Color(255, 255, 255));
            jButton5.setText("ADD");
            jButton5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton5ActionPerformed(evt);
                }
            });

            jLabel11.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
            jLabel11.setText("PRODUCT ID : ");

            pnamea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            pnamea.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    pnameaActionPerformed(evt);
                }
            });

            jLabel13.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
            jLabel13.setText("PRODUCT NAME : ");

            ppa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            ppa.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ppaActionPerformed(evt);
                }
            });

            jLabel14.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
            jLabel14.setText("PRODUCT PRICE : ");

            jLabel15.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
            jLabel15.setText("QUANTITY :");

            pqa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            pqa.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    pqaActionPerformed(evt);
                }
            });

            tb3.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "ID", "NAME", "PRICE", "QUANTITY", "TOTAL PRICE"
                }
            ));
            jScrollPane3.setViewportView(tb3);

            javax.swing.GroupLayout PALayout = new javax.swing.GroupLayout(PA);
            PA.setLayout(PALayout);
            PALayout.setHorizontalGroup(
                PALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PALayout.createSequentialGroup()
                    .addGroup(PALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PALayout.createSequentialGroup()
                            .addGroup(PALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PALayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(PALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PALayout.createSequentialGroup()
                                            .addGroup(PALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel13))
                                            .addGap(14, 14, 14)
                                            .addGroup(PALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pida, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(pnamea, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(PALayout.createSequentialGroup()
                                            .addGroup(PALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel14)
                                                .addComponent(jLabel15))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(PALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pqa, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ppa, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(PALayout.createSequentialGroup()
                                    .addGap(298, 298, 298)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 196, Short.MAX_VALUE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap())
            );
            PALayout.setVerticalGroup(
                PALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PALayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addGroup(PALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(PALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pnamea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(PALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ppa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(PALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pqa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(55, 55, 55)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(74, Short.MAX_VALUE))
            );

            pu.setAutoscrolls(true);
            pu.setMinimumSize(new java.awt.Dimension(800, 800));

            pid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            pid.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    pidActionPerformed(evt);
                }
            });

            jButton6.setBackground(new java.awt.Color(0, 0, 0));
            jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jButton6.setForeground(new java.awt.Color(255, 255, 255));
            jButton6.setText("UPDATE");
            jButton6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton6ActionPerformed(evt);
                }
            });

            jLabel12.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
            jLabel12.setText("PRODUCT ID : ");

            pname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            pname.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    pnameActionPerformed(evt);
                }
            });

            jLabel16.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
            jLabel16.setText("PRODUCT NAME : ");

            pp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            pp.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ppActionPerformed(evt);
                }
            });

            jLabel17.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
            jLabel17.setText("PRODUCT PRICE : ");

            jLabel18.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
            jLabel18.setText("QUANTITY :");

            pq.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            pq.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    pqActionPerformed(evt);
                }
            });

            tb4.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "ID", "NAME", "PRICE", "QUANTITY", "TOTAL PRICE"
                }
            ));
            jScrollPane4.setViewportView(tb4);

            javax.swing.GroupLayout puLayout = new javax.swing.GroupLayout(pu);
            pu.setLayout(puLayout);
            puLayout.setHorizontalGroup(
                puLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(puLayout.createSequentialGroup()
                    .addGroup(puLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(puLayout.createSequentialGroup()
                            .addGroup(puLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(puLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(puLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(puLayout.createSequentialGroup()
                                            .addGroup(puLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel16))
                                            .addGap(14, 14, 14)
                                            .addGroup(puLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(puLayout.createSequentialGroup()
                                            .addGroup(puLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel17)
                                                .addComponent(jLabel18))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(puLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pq, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(pp, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(puLayout.createSequentialGroup()
                                    .addGap(298, 298, 298)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 196, Short.MAX_VALUE))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap())
            );
            puLayout.setVerticalGroup(
                puLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(puLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addGroup(puLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(puLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(puLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(puLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(55, 55, 55)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(74, Short.MAX_VALUE))
            );

            PD.setAutoscrolls(true);
            PD.setMinimumSize(new java.awt.Dimension(800, 800));

            idd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            idd.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    iddActionPerformed(evt);
                }
            });

            jButton7.setBackground(new java.awt.Color(0, 0, 0));
            jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jButton7.setForeground(new java.awt.Color(255, 255, 255));
            jButton7.setText("DELETE");
            jButton7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton7ActionPerformed(evt);
                }
            });

            jLabel19.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
            jLabel19.setText("PRODUCT ID : ");

            tb5.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "ID", "NAME", "PRICE", "QUANTITY", "TOTAL PRICE"
                }
            ));
            jScrollPane5.setViewportView(tb5);

            javax.swing.GroupLayout PDLayout = new javax.swing.GroupLayout(PD);
            PD.setLayout(PDLayout);
            PDLayout.setHorizontalGroup(
                PDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PDLayout.createSequentialGroup()
                    .addGroup(PDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PDLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel19)
                            .addGap(79, 79, 79)
                            .addComponent(idd, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 207, Short.MAX_VALUE))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap())
                .addGroup(PDLayout.createSequentialGroup()
                    .addGap(281, 281, 281)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            PDLayout.setVerticalGroup(
                PDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PDLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addGroup(PDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(243, Short.MAX_VALUE))
            );

            jMenu1.setText("File");

            jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
            jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zubair/download.jpg"))); // NOI18N
            jMenuItem2.setText("EMPLOYEE");
            jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jMenuItem2MouseClicked(evt);
                }
            });
            jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem2ActionPerformed(evt);
                }
            });
            jMenu1.add(jMenuItem2);
            jMenu1.add(jSeparator6);

            jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
            jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zubair/Untitled.png"))); // NOI18N
            jMenuItem1.setText("EXIT");
            jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem1ActionPerformed(evt);
                }
            });
            jMenu1.add(jMenuItem1);

            jMenuBar1.add(jMenu1);

            MEN3.setText("Employee Record");

            jMenuItem3.setText("INSERT OR UPDATE RECORD");
            jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem3ActionPerformed(evt);
                }
            });
            MEN3.add(jMenuItem3);
            MEN3.add(jSeparator3);

            jMenuItem5.setText("DELETE RECORD");
            jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem5ActionPerformed(evt);
                }
            });
            MEN3.add(jMenuItem5);

            jMenuBar1.add(MEN3);

            MEN4.setText("Product Record");

            jMenuItem6.setText("PRODUCT ADDED");
            jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem6ActionPerformed(evt);
                }
            });
            MEN4.add(jMenuItem6);
            MEN4.add(jSeparator4);

            jMenuItem7.setText("PRODUCT UPDATE");
            jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem7ActionPerformed(evt);
                }
            });
            MEN4.add(jMenuItem7);
            MEN4.add(jSeparator5);

            jMenuItem8.setText("PRODUCT DELETE");
            jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem8ActionPerformed(evt);
                }
            });
            MEN4.add(jMenuItem8);

            jMenuBar1.add(MEN4);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 20, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap()))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(THANKS, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap()))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap()))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap()))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 31, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap()))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(THANKS, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(PA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap()))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(62, 62, 62)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(42, 42, 42)))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new admin().dispose();
        new NewJFrame().setVisible(true);
       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
       THANKS.setVisible(false);
       ar.setVisible(true);
       ad.setVisible(false);
       PA.setVisible(false);
       LOGIN.setVisible(false);
       PD.setVisible(false);
       pu.setVisible(false);
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
               // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void idrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idrActionPerformed

    private void usrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        
             try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String a = "jdbc:sqlserver://"+dblink+";databaseName="+db+";integratedSecurity=true;";

            Connection con = DriverManager.getConnection(a);
            String q = "insert into emp values("+idr.getText()+",'"+usr.getText()+"','"+psr.getText()+"')";
            Statement st = con.createStatement();
            st.executeUpdate(q);
            
           
         }catch (Exception ex) {
            System.out.println(ex);
        }     
        dtm.getDataVector().removeAllElements();
             try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String a = "jdbc:sqlserver://"+dblink+";databaseName="+db+";integratedSecurity=true;";

            Connection con = DriverManager.getConnection(a);
            String q = "select * from emp";
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery(q);
             while (rs.next()) {
                 dtm.addRow(new Object[]{rs.getInt("id"),rs.getString("username"),rs.getString("password")});
                 
             }
         }catch (Exception ex) {
            System.out.println(ex);
        }     
        
        idr.setText("");
        usr.setText("");
        psr.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
          try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String a = "jdbc:sqlserver://"+dblink+";databaseName="+db+";integratedSecurity=true;";

            Connection con = DriverManager.getConnection(a);
            String q = "update emp set username='"+usr.getText()+"',password='"+psr.getText()+"' where id = "+idr.getText();
;            Statement st = con.createStatement();
            st.executeUpdate(q);
            
           
         }catch (Exception ex) {
            System.out.println(ex);
        }     
        dtm.getDataVector().removeAllElements();
             try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String a = "jdbc:sqlserver://"+dblink+";databaseName="+db+";integratedSecurity=true;";

            Connection con = DriverManager.getConnection(a);
            String q = "select * from emp";
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery(q);
             while (rs.next()) {
                 dtm.addRow(new Object[]{rs.getInt("id"),rs.getString("username"),rs.getString("password")});
                 
             }
         }catch (Exception ex) {
            System.out.println(ex);
        }     
        idr.setText("");
        usr.setText("");
        psr.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void idr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idr1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String a = "jdbc:sqlserver://"+dblink+";databaseName="+db+";integratedSecurity=true;";

            Connection con = DriverManager.getConnection(a);
            String q = "delete from emp where id = "+idr1.getText();
;            Statement st = con.createStatement();
            st.executeUpdate(q);
            
           
         }catch (Exception ex) {
            System.out.println(ex);
        }     
        dtm.getDataVector().removeAllElements();
             try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String a = "jdbc:sqlserver://"+dblink+";databaseName="+db+";integratedSecurity=true;";

            Connection con = DriverManager.getConnection(a);
            String q = "select * from emp";
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery(q);
             while (rs.next()) {
                 dtm.addRow(new Object[]{rs.getInt("id"),rs.getString("username"),rs.getString("password")});
                 
             }
         }catch (Exception ex) {
            System.out.println(ex);
        }     
   idr.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void pidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        
             try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String a = "jdbc:sqlserver://"+dblink+";databaseName="+db+";integratedSecurity=true;";

            Connection con = DriverManager.getConnection(a);
            int l;
    l = Integer.parseInt(ppa.getText());
            int b=Integer.parseInt(pqa.getText());
            String q = "insert into pro values("+pida.getText()+",'"+pnamea.getText()+"',"+ppa.getText()+","+pqa.getText()+","+l*b+")";
            Statement st = con.createStatement();
            st.executeUpdate(q);
            
           
         }catch (Exception ex) {
            System.out.println(ex);
        }     
dtma.getDataVector().removeAllElements();
             try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String a = "jdbc:sqlserver://"+dblink+";databaseName="+db+";integratedSecurity=true;";

            Connection con = DriverManager.getConnection(a);
            String q = "select * from pro";
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery(q);
             while (rs.next()) {
                 dtma.addRow(new Object[]{rs.getInt("id"),rs.getString("name"),rs.getInt("price"),rs.getInt("quantity"),rs.getInt("total_price")});
                 
             }
         }catch (Exception ex) {
            System.out.println(ex);
        }     
        
   
pida.setText("");
pnamea.setText("");
ppa.setText("");
pqa.setText("");

        
        
        
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void pnameaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameaActionPerformed

    private void ppaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppaActionPerformed

    private void pqaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pqaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pqaActionPerformed

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String a = "jdbc:sqlserver://"+dblink+";databaseName="+db+";integratedSecurity=true;";
 int l;
    l = Integer.parseInt(ppa.getText());
            int b=Integer.parseInt(pqa.getText());
            Connection con = DriverManager.getConnection(a);
            String q = "update emp set name='"+pname.getText()+"',price="+pp.getText()+",quantity="+pq.getText()+",total_price="+l*b+" where id = "+pid.getText();
            
;            Statement st = con.createStatement();
            st.executeUpdate(q);
            
           
         }catch (Exception ex) {
            System.out.println(ex);
        }     

dtma.getDataVector().removeAllElements();
             try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String a = "jdbc:sqlserver://"+dblink+";databaseName="+db+";integratedSecurity=true;";

            Connection con = DriverManager.getConnection(a);
            String q = "select * from pro";
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery(q);
             while (rs.next()) {
                 dtma.addRow(new Object[]{rs.getInt("id"),rs.getString("name"),rs.getInt("price"),rs.getInt("quantity"),rs.getInt("total_price")});
                 
             }
         }catch (Exception ex) {
            System.out.println(ex);
        }     
        
pid.setText("");
pname.setText("");
pp.setText("");
pq.setText("");



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void ppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppActionPerformed

    private void pqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pqActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String a = "jdbc:sqlserver://"+dblink+";databaseName="+db+";integratedSecurity=true;";

            Connection con = DriverManager.getConnection(a);
            String q = "delete from emp where id = "+idd.getText();
;            Statement st = con.createStatement();
            st.executeUpdate(q);
            
           
         }catch (Exception ex) {
            System.out.println(ex);
        }
        
dtma.getDataVector().removeAllElements();
             try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String a = "jdbc:sqlserver://"+dblink+";databaseName="+db+";integratedSecurity=true;";

            Connection con = DriverManager.getConnection(a);
            String q = "select * from pro";
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery(q);
             while (rs.next()) {
                 dtma.addRow(new Object[]{rs.getInt("id"),rs.getString("name"),rs.getInt("price"),rs.getInt("quantity"),rs.getInt("total_price")});
                 
             }
         }catch (Exception ex) {
            System.out.println(ex);
        }     
        idd.setText("");
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void iddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (ps.getText().equals("admin")) {
            LOGIN.setVisible(false);
            THANKS.setVisible(true);
            MEN3.setEnabled(true);
            MEN4.setEnabled(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"YOUR PASSWORD IS WRONG");
            ps.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
         new admin().dispose();
        
        
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
 THANKS.setVisible(false);
       ar.setVisible(false);
       ad.setVisible(true);
       PA.setVisible(false);
       LOGIN.setVisible(false);
       PD.setVisible(false);
       pu.setVisible(false);
        
 
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
      THANKS.setVisible(false);
       ar.setVisible(false);
       ad.setVisible(false);
       PA.setVisible(true);
       LOGIN.setVisible(false);
       PD.setVisible(false);
       pu.setVisible(false);
        
        
        
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        THANKS.setVisible(false);
       ar.setVisible(false);
       ad.setVisible(false);
       PA.setVisible(false);
       LOGIN.setVisible(false);
       PD.setVisible(false);
       pu.setVisible(true);
        
        
        
        
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        THANKS.setVisible(false);
       ar.setVisible(false);
       ad.setVisible(false);
       PA.setVisible(false);
       LOGIN.setVisible(false);
       PD.setVisible(true);
       pu.setVisible(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LOGIN;
    private javax.swing.JMenu MEN3;
    private javax.swing.JMenu MEN4;
    private javax.swing.JPanel PA;
    private javax.swing.JPanel PD;
    private javax.swing.JPanel THANKS;
    private javax.swing.JPanel ad;
    private javax.swing.JPanel ar;
    private javax.swing.JTextField idd;
    private javax.swing.JTextField idr;
    private javax.swing.JTextField idr1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pida;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField pnamea;
    private javax.swing.JTextField pp;
    private javax.swing.JTextField ppa;
    private javax.swing.JTextField pq;
    private javax.swing.JTextField pqa;
    private javax.swing.JPasswordField ps;
    private javax.swing.JPasswordField psr;
    private javax.swing.JPanel pu;
    private javax.swing.JTable tb1;
    private javax.swing.JTable tb2;
    private javax.swing.JTable tb3;
    private javax.swing.JTable tb4;
    private javax.swing.JTable tb5;
    private javax.swing.JTextField usr;
    // End of variables declaration//GEN-END:variables
}
